smallflat/index.html

テスト用index.htmlです

---

tani/index.html
tani/style.css

tani_commit

---

NK/index.html

first commit

---

reeve/index.html

- りーべ用ディレクトリを作成しました
- index.htmlを追加しました

りーべ用index.htmlを追加しました！

---

Datchlive/index.html

Datch用index.htmlを追加しました。

---

etochan/index.html

etochan用index.htmlを追加しました！

---

yama_dir/index.html

add index.html

---

masayoshi999_dir/index.html
masayoshi999_dir/style.css

index.html style.css を追加

---

magako/index.html
magako/style.css

magako フォルダを追加しました！
フォルダの中身は以下です。
- index.html
- style.css

add magako directory

---

rio_m/index.html
rio_m/style.css

ファイルを作成しました。

---

wi-tech/index.html

- wi-techフォルダを追加
index.htmlファイルを新規追加しました。

✨ add index.html for wi-tech.

---

miki_test/index.html

miki用のindex.htmlを追加しました。

---

gabriel_wong/index.html

I've added Gabriel Wong's index.html.

---

yamamoto-test/index.html

index.htmlを追加してみた。

---

medi/index.html

index.html を追加しました。

---

yuji_23/index.html

yuji用index.html追加しました！

---

yuugurekun/index.html

- index.htmlファイルを追加しました
- 詳細
- 詳細
- 詳細

yuugurekun用index.htmlを追加しました！

---

mo_ri_regen/index.html
mo_ri_regen/style.css

mo_ri_regen

---

yoshifoxor/index.html

yoshifoxor の index.html を追加しました。

index.html を追加

---

rinka/index.html

index.htmlの変更

---

airi_test/index.html

あいり用index.htmlを追加しました

---

mattun/saqla/index.html

initial commit

---

yamamoto-test/style.css

styleも追加してみた

---

mattun/saqla/style.css

add style.css

---

lhotse2_test/index.html
lhotse2_test/style.css

修正&追加いたしました

---

mari_it/index.html

index.htmlを追加

---

.vscode/moritarou/index.html

gitHubのテストとして、赤文字でヘッダー部にコメントを入れました。

comment-in-header

---

confe/index.html

インデックスファイルを作成しました

---

shoasas/index.html

shoasas index.htmlを追加しました（テスト）

---

shoasas/index.html

Reverts qin-salon/learn-git#124

Revert "shoasas index.htmlを追加しました（テスト）"

---

maimu_test/index.html

マイム用index.htmlを追加しています！

---

yamapan/index.html

index.htmlを追加しました。

---

test_hiro/index.html

index.htmlのコミットです。

---

takataka_test/index.html

こんな感じでindex.htmlを変更しました。
ご確認お願いします。

index.htmlを変更しました

---

oreyoshi/index.html

oreyoshi用index.htmlを追加しました！

---

oreyoshi/index.html

Reverts qin-salon/learn-git#146

Revert "oreyoshi用index.htmlを追加しました！"

---

nakakou/index.html

nakahiyoのindex.htmlを作成しました

---

YU-KI/index.html

YU-KI用index.htmlを追加しました。

---

norton/index.html

・テスト用のindex.htmlを作成しました
・テストです
・いろいろ学んでいきたいです

index.htmlを作成

---

kouyamadir/index.css
kouyamadir/index.html

kouyamaのhtml,cssを追加しました

---

koh/index.html

koh用index.htmlを追加しまいた

---

kijikunnn/index.html

きじくん用index.htmlを追加しました

---

Hi6kaz/index.html
Hi6kaz/style.css

HTMLとcssを追加しました。

---

index.html

index.htmlを追加します！！

---

shirai_test/index.html

シライ用index.htmlを追加しました！

---

shirai_test/style.css

CSSも追加しました。

---

ken/index.html

index.htmlを追加しました

---

blueberry_cake/index.html

add index.html practice

---

kwnkt_it/index.html

htmlを編集しました！

---

takuro_git/index.html

たくろー用index.htmlを追加しました！

---

poooo_test/index.html
poooo_test/style.css

- index.html（タイトル、テキスト追加）
- style.css（余白、フォントサイズ・カラー追加）

HTML&CSSを追加したよ！！！！！

---

kosuke_test/index.html
kosuke_test/style.css

Kosuke test

---

tatsukennBs_test/index.html

index.html新規作成しました。

---

t0m0fum100001/index.html

Tomofumi111テスト

---

.vscode/shiruyama/index.html

Reverts qin-salon/learn-git#262

Revert "しるやま用index.htmlを追加しました"

---

kaki_08/index.html

かーき用　✨ index.htmlを追加しました

---

imokenpi/imokenpi.html

branch test

---

kenken/index.html
kenken/style.css

個人用に以下ファイルを追加しました。
・index.html
・style.css

kenken用 First commit

---

geya/index.html

🎉 first commit

---

santsbarcelo/index.html

さんつ用index.htmlを追加しました！

---

jaga_tori/index.html

（テスト）index.htmlを追加しました

---

toyoaki_git/index.html

Toyoaki用index.htmlを追加しました!

---

tiger_otter/index.html

tigerottrer用index.htmlを追加しました。

---

choma/index.html

✨ index.htmlを追加しました

---

yakumo/style.css

index.htmlの追加をしました
